#Configure the Server Port
server:
  port: 7001
  
spring:
  application:
   name: COURSE-SERVICE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mocktest
    username: root
    password: Rathod@01

